<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxAssociadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxAssociadosRepository extends EntityRepository
{
    public function findByPesquisas($nome)
    {
        /**
         * @var $associados \Pax\Entity\PaxAssociados
         */
        $associados = $this->createQueryBuilder('a')
            ->where('a.nome = :b1')
            ->setParameter('b1', $nome)->getQuery()->getResult();
        if(!empty($associados)):
            return $associados;
        else :
            return false;
        endif;

    }

    public function findIdAssociado($nome){
        /**
         * @var $associados \Pax\Entity\PaxAssociados
         */
        $associados = $this->createQueryBuilder('a')
            ->where('a.nome = :b1')
            ->setParameter('b1', $nome)->getQuery()->getArrayResult();
        $id = $associados[0]['id'];
        //var_dump($id);die();
        if(!empty($id)):
            return $id;
        else :
            return false;
        endif;
    }

    public function findByCodAssoiado(){
        /**
         * @var $associados \Pax\Entity\PaxEmpresas
         */
        $associados = $this->createQueryBuilder('a')
            ->select('max(a.id)')
            ->orderBy('a.id', 'desc')
            ->setMaxResults(1)
            ->getQuery()->getResult();
        return $associados;
    }

    public function findByNomeLike($nome){
        $associados = $this->createQueryBuilder('a')
            ->where('a.nome like :n1')
            ->setParameter('n1','%'.$nome.'%')
            ->getQuery()
            ->getArrayResult()
        ;
        return $associados;
    }

    public function AssociadoMensalidade($inicial, $final)
    {
        /**
         * @var $associados \Pax\Entity\PaxAssociados
         */
        $associados = $this->createQueryBuilder('a')
            ->where('a.id >= :i1')
            ->andWhere('a.id <= :f1')
            ->setParameter('i1', $inicial)
            ->setParameter('f1', $final)
            //->setParameters(array('i1', $inicial),array('f1',  $final))
            ->getQuery()
            ->getArrayResult()
            ;
        //var_dump($associados);die("PaxAssociadoRepository L 65");
        return $associados;

    }

}