<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;
use Pax\Entity\PaxFuncionarios;

/**
 * PaxFuncionariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxFuncionariosRepository extends EntityRepository
{
    public function findByLogin(PaxFuncionarios $funcionarios, $login, $senha)
    {
        /**
         * @var $funcionarioLogin \Pax\Entity\PaxFuncionarios
         */
        $funcionarioLogin = $this->createQueryBuilder('f')
            ->where('f.login = :a1')
            ->setParameter('a1', $login)
            ->getQuery()
            ->getOneOrNullResult();
        //var_dump($funcionarios);die;

        if(!empty($funcionarioLogin)):
            $funcionarios->setSalt($funcionarioLogin->getSalt());
            if($funcionarios->encryptSenha($senha) == $funcionarioLogin->getSenha()):
                $funcionario = $funcionarioLogin->toArray();
                unset($funcionario['senha']);
                unset($funcionario['salt']);
                //var_dump($funcionario);die("Re-PaxFuncionariosRepository - L33");
                return $funcionario ;
            endif;

        endif;

        return false;
    }
}