<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxMaterialRepository extends EntityRepository
{
}
