<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxMensalidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxMensalidadeRepository extends EntityRepository
{
    public function findByAno($id)
    {
        $ano = $this->createQueryBuilder('m')
            ->where('m.idAssociado = :a1')
            ->setParameter('a1' , $id)
            ->addGroupBy('m.anoReferencia')
            ->getQuery()
            ->getResult();
        //var_dump($ano);die("PaxMensalidadeRepository L 22");
        return $ano;
    }
}
