<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxMovimentoCaixaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxMovimentoCaixaRepository extends EntityRepository
{
    public function totalDebito(){
        $debito = $this->createQueryBuilder('d')
            ->select('sum(d.valorLancado)')
            ->where('d.tipo = :t')
            ->setParameter('t', 'D')
            ->setMaxResults(1)
            ->getQuery()->getArrayResult();

        return $debito;
    }

    public function totalCredito(){
        $credito = $this->createQueryBuilder('d')
            ->select('sum(d.valorLancado)')
            ->where('d.tipo = :t')
            ->setParameter('t', 'C')
            ->setMaxResults(1)
            ->getQuery()->getArrayResult();

        return $credito;
    }

    public function moviData($dataInicio,$dataFinal){
        $data = $this->createQueryBuilder('m')
            ->where('m.dataMovimento >= :d')
            ->andWhere('m.dataMovimento <= :f')
            ->setParameter('d',$dataInicio)
            ->setParameter('f',$dataFinal)
            ->getQuery()
            ->getResult();
        //var_dump($data);die();
        return $data;
    }
}
