<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxObitosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxObitosRepository extends EntityRepository
{
    public function findByPesquisas($nome)
    {
        /**
         * @var $obitos \Pax\Entity\PaxObitos
         */
        $obitos = $this->createQueryBuilder('o')
            ->where('o.nome like :b1')
            ->setParameter('b1', '%'.$nome.'%')
            ->getQuery()
            ->getArrayResult();
        if(!empty($obitos)):
            return $obitos;
        else :
            return false;
        endif;

    }
}
