<?php

namespace Pax\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaxUrnasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaxUrnasRepository extends EntityRepository
{
}
