<!DOCTYPE html>
<html lang="pt_BR">
<head>
    <meta charset="utf-8">
    <title>Upload </title>
    <style type="text/css">
        <!--
        a:link {
            color: #000;
            text-decoration: none;
        }
        a:visited {
            text-decoration: none;
            color: #000;
        }
        a:hover {
            text-decoration: none;
        }
        a:active {
            text-decoration: none;
        }
        body {
            background-color: #FFF;
        }
        -->
    </style></head>
<link rel="stylesheet" href="estilo.css">
<body>
<form action="/app-pax/geraFor/import" method="post" enctype="multipart/form-data">
    <table width="338" border="1" cellpadding="0" cellspacing="0">
        <tr>
            <td width="334">
                <table width="335" border="0">
                    <tr>
                        <td width="126" bordercolor="" align="center" bgcolor="#86B720"><h3>Upload de Arquivo CSV</h3></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="file" name="arquivo"></td>
                    </tr>
                </table>
                <p></p></td>
        </tr>
        <tr>
            <td align="center"><input type="submit" value="Enviar" style="width:100px; height:35px;"></td>
        </tr>
    </table>
</form>
</body>
</html>
