<div class="topo-table">
    <a href="<?php echo $this->url('pax-geraMensalidade/default', array('action' => 'inserir'))?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

</div>

<br />

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Lista Controle de Mensalidades
        </div>
    </div>
</div>

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Cobrador</th>
            <th>Ano Referencia</th>
            <th>Mens Referencia</th>
            <th>Data Criação</th>
            <th>Total em Aberto</th>
            <th>Total Pago</th>
            <th>Condição</th>
            <th>Status</th>
        </tr>
        </thead>

        <tbody>
        <?php
        /**
         * @var $entity \Pax\Entity\PaxGeraMensalidade
         */
        ?>
        <?php  if ($this->data): ?>
            <?php foreach ($this->data as $entity): ?>
                <tr>
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getIdCobrador()->getNome(); ?></td>
                    <td><?php echo $entity->getAnoReferencia(); ?></td>
                    <td><?php echo $entity->getMesReferencia(); ?></td>
                    <td><?php echo ($entity->getDataCriacao()) ? $entity->getDataCriacao()->format('d/m/Y') : ""; ?></td>
                    <td><?php echo "EmAberto" ?></td>
                    <td><?php echo "Pago" ?></td>
                    <td><?php echo "Relatorio" ?></td>


                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <p>Nem um Registro foi Encontrado</p>
        <?php endif;  ?>
        </tbody>
    </table>

    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator', array('router' => 'pax-geraMensalidade/paginator')); ?>


    <?php $this->headScript()->captureStart(); ?>
    $(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('pax-geraMensalidade/default', array("action" => "excluir")); ?>' + '/';

    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
    // variável contendo o id referente ao botão clicado
    var admin_id  = $(this).attr('href').split(url_deletar).pop();
    // variável contendo mensagem da janela
    var mensagem = "Deseja realmente apagar o Associado com ID " + admin_id + "?";
    // variável com resposta da mensagem colocada na janela
    var confirmacao = confirm(mensagem);

    // se a confirmação for false o fluxo é interrompido
    if (!confirmacao)
    // elimar o evendo do botão clicado
    event.preventDefault();
    });
    });
<?php $this->headScript()->captureEnd(); ?>