<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Gerar Grupo de Mensalidades
        </div>
    </div>

    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('pax-geraMensalidade/default', array('controller' => 'GeraMensalidade', 'action' => 'inserir')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>

    <div class="panel-body ">

        <div class="container">



            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Valor.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('valorCobranca'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('valorCobranca'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cobrador.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('cobrador'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('cobrador'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Mês Ref.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('mesReferencia'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('mesReferencia'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Ano Ref.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('anoReferencia'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('anoReferencia'));
                        ?>
                    </div>
                </div>
            </div>

        </div>

    </div>


    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Gerar Mensalidades</button>
        <a href="<?php echo $this->url('pax-geraMensalidade'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>


</div>