<?php

namespace DoctrineORMModule\Proxy\__CG__\Pax\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaxFuncionarios extends \Pax\Entity\PaxFuncionarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'id', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'nome', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'login', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'senha', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cep', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'estado', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cidade', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'endereco', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'rg', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cpf', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'comissao', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'dataAdm', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'salt', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'status');
        }

        return array('__isInitialized__', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'id', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'nome', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'login', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'senha', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cep', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'estado', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cidade', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'endereco', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'rg', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'cpf', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'comissao', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'dataAdm', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'salt', '' . "\0" . 'Pax\\Entity\\PaxFuncionarios' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaxFuncionarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptSenha', array($senha));

        return parent::encryptSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', array($cidade));

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', array());

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', array($endereco));

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', array());

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setRg($rg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', array($rg));

        return parent::setRg($rg);
    }

    /**
     * {@inheritDoc}
     */
    public function getRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', array());

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', array($cpf));

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', array());

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setComissao($comissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComissao', array($comissao));

        return parent::setComissao($comissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getComissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComissao', array());

        return parent::getComissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAdm($dataAdm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAdm', array($dataAdm));

        return parent::setDataAdm($dataAdm);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAdm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAdm', array());

        return parent::getDataAdm();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

}
