<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Urna
        </div>
    </div>
    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('pax-urnas/default', array('controller' => 'urnas', 'action' => 'editar', 'id' => $this->id)));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel-body ">

        <div class="container">

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Descrição.:</label>
                    <div class='col-lg-8  col-md-8'>
                        <?php
                        // renderiza html input
                        echo $this->formTextarea($form->get('descricao'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('descricao'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Saldo.:</label>
                    <div class='col-lg-2 col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('saldo'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('saldo'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Compra.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('compra'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('compra'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Venda.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('venda'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('venda'));
                        ?>
                    </div>

                </div>
            </div>


        </div>

    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Salvar Urna</button>
        <a href="<?php echo $this->url('pax-urnas'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>
