<?php /*
<script>
    jQuery(document).ready(function(){
        $( "#codigo_ass" ).combogrid({
            url: '<?php echo $this->url('pax-obitos/default', array('action' => 'pesquisas'))?>',
            debug:true,
            //replaceNull: true,
            colModel: [{'columnName':'contrato','width':'20','label':'Contato'}, {'columnName':'cod_associado','width':'10','label':'cod_associado'}, {'columnName':'nome','width':'60','label':'Nome'}],
            select: function( event, ui ) {

                $( "#codigo_ass" ).val( ui.item.cod_associado );
                $( "#nome_associado" ).val( ui.item.nome );
                $( "#contrato" ).val( ui.item.contrato );
                return false;
            }
        });
    });
</script>
*/ ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Nova Obito
        </div>
    </div>
    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('pax-obitos/default', array('controller' => 'obitos', 'action' => 'inserir')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel-body ">

        <div class="container">

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Situação.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('situacao'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('situacao'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cód.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('codigo_ass'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('codigo_ass'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Nome.:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('nome_associado'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('nome_associado'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Obito.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('data_obito'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('data_obito'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Velorio.:</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('velorio'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('velorio'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cidade.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('cidade'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('cidade'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Pagamento.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('tipo_pagamento'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('tipo_pagamento'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Contrato.:</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('contrato'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('velorio'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cidade.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('contrato'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('contrato'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Grupo.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('groupo'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('groupo'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Translado.:</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('translado'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('translado'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Responsavel.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('responsavel'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('responsavel'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Dia Pag.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('data_pagamento'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('data_pagamento'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cód Urna</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('cod_urna'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('cod_urna'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>ValorUrna.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('valor_urna'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('valor_urna'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Diferença.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('diferenca_urna'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('diferenca_urna'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Funcionario.:</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('atendente'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('atendente'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Horario.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('horario_sepultamento'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('horario_sepultamento'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Valor.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('valor_total'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('valor_total'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Descrição.:</label>
                    <div class='col-lg-3 col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('descricao'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('descricao'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Translado.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('valor_tran'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('valor_tran'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Data Velorio.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('data_velorio'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('data_velorio'));
                        ?>
                    </div>
                </div>
            </div>




        </div>

    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Salvar Obito</button>
        <a href="<?php echo $this->url('pax-obitos'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>
