<meta charset="utf-8">
<?php
    /**
     * @var $entity \Pax\Entity\PaxAssociados
     */
    foreach($this->dados as $entity):
?></b>
<p>Pelo presente instrumento particular de PRESTAÇÃO DE SERVIÇO, de um lado, JOÃO BATISTA ADAIR, pessoa jurídica de direito privado,
    sediada nesta cidade, registrado no CNPJ: 37.587.045/0001-14. Cadastro Municipal 1.647 neste ato representa pelo diretor responsável
    INFINE doravante denominado simplesmente FUNERARIA PAX VILA BOA e de outro contratante:
    Sr (a): <b><?= $entity->getNome(); ?></b>, Grupo: <b><?= $entity->getSerie(); ?></b>, Residente à: <b><?= $entity->getEndereco(); ?></b>, Bairro:
    <b><?= $entity->getBairro(); ?></b>,  Cont.: <b><?= $entity->getContrato(); ?></b>, Tem entre si, justo e contratado o seguinte:
</p>
<p>1. FUNERARIA PAX VILA BOA, organização especializada no atendimento de serviços funerários em geral, obriga-se a prestar ao
    Contratante e aos seus ascendentes e descendentes direitos sob comprovada dependência econômica dele, enumerados no item 1 (um)
    do regulamento constante no verso deste contrato as condições abaixo estabelecidas.</p>
<p>Parágrafo Único: Perderão os direitos assegurados por este contrato os dependentes que vierem contrair matrimônio ou mantiverem
    união conjugal extra-matrimônio.</p>
<p>
    2. O CONTRATANTE pagará a PAX VILA BOA no ato da assinatura do presente CONTRATO, a título de Contra prestação de serviços ou
    administração, como taxa de inscrição e sem direito a restituição, seja a que titulo for, a importância de R$  _______
</p>
<p>
    3. O CONTRATANTE pagará a PAX VILA BOA, a titulo de manutenção, mensalmente uma taxa equivalente a <b><?= $entity->getTipoContrato(); ?></b>
    % sobre o valor vigente do salário mínimo no mês do pagamento, cuja finalidade é a cobertura das despesas com materiais e serviços
    para sepultamento do contratante e seus dependentes.
</p>
<p>
    3.1 O pagamento da taxa de manutenção indicada na clausula 3 deste contrato, tem por finalidade profícua exclusiva, remunerar a
    PAX VILA BOA pela administração e despesas com matérias e serviços nela indicados
</p>
<p>
    4. O prazo de carência do presente CONTRATO é de 90 (noventa) dias, a contar da data de assinatura deste, devendo o CONTRATANTE
    estar em dias com suas obrigações, sob pena de perder os direitos aos serviços aqui contratados.
</p>
<p>
    4.1 Óbitos na carência: Em caso de óbito na carência fica garantido ao associado o desconto de 50 % do serviço contratado.
</p>
<p>
    5. O CONTRATANTE terá sua inscrição cancelada independente de qualquer notificação judicial ou Extrajudicial, sem direito a
    restituição do que houver pago, nas seguintes hipóteses:
</p>
<p>
    A) Atrasar por 3 (três) vezes consecutivas o pagamento das contribuições relativas ao serviços, e previsto na clausula 3 do
    presente contrato;
</p>
<p>
    B) For comprovada inexatidão das declarações no que se refere a inscrição ou atendimento dos beneficiários;
</p>
<p>
    C) O prazo Maximo permitido será 90(noventa) dias, passado este prazo a FUNERARIA PAX VILA, não se responsabilizara pelo atendimento;
</p>
<p>
    D) Após 90(noventa) dias de atraso, o CONTRATANTE terá sua inscrição paralisada, sem direito a restituição, nos termos da clausula 5 “caput”;
</p>
<p>
    6. As garantias asseguradas por este contrato serão imediatamente suspensas em caso de calamidade publica como cataclismas,
    catástrofes, epidemias, guerra civil ou quaisquer motivos advindos de caso fortuito ou força maior.
</p>
<p>
    7. A FUNERARIA PAX VILA BOA não se responsabilizara por quaisquer despesas feitas pelo contratante, a não ser quando por
    ela autorizada por escrito.
</p>
<p>
    8. O CONTRATANTE deverá comunicar a FUNERARIA PAX VILA BOA imediatamente os falecimentos cobertos pelo contrato.
</p>
<p>
    9. Havendo necessidade de transportar o corpo para o local situado fora da aérea de atendimento da FUNERARIA PAX VILA BOA;
    ao CONTRATANTE e seus dependentes, será cobrado esse transporte superior a  _________  km, o mesmo acontecendo quando se
    fizer necessário o transporte de outra localidade para área de atendimento, compreende-se por área de atendimento o perímetro
    urbano do local contratado
</p>
<p>
    9.1 Fica eleito para fins da clausula 9, como área de atendimento, a Cidade de<br>
    Estado de Goiás (Distrito e Município)
</p>
<p>
    10. Caso seja requisitado pelo Contratante, ou por qualquer um dos seus benefícios, transporte do corpo para local diverso
    do estabelecido no item 9 deste contrato, ou seja, para local fora da área de atendimento ( do Município e Distrito de Goiás – GO),
    será cobrado a quilometragem superior a    _____    km, o mesmo ocorrerá quando for solicitado o transporte do corpo de outra
    localidade para dentro da área de atendimento, ou seja, as despesas com transporte superior a  _____     km serão arcadas pelo
    Contratante e ou, seus beneficiários
</p>
<p>
    11. Na hipótese de falecimento do Contratante, os seus herdeiros ou sucessores responderão pelas obrigações ora assumidas,
    assistindo-lhes por igual todos os direitos decorrentes deste contrato
</p>
<p>
    12. O CONTRATANTE obriga-se a manter atualizado, junto a FUNERARIA PAX VILA BOA o endereço de sua residência para que haja
    atendimento mais rápido.
</p>
<p>
    13. Para os dependentes inscritos neste contrato cuja medida de urna mortuária não alcance o tamanho normal, 2 (dois) metros, o
    CONTRATANTE será atendido ao tempo de óbito, (sujeitando-se ao material requisitado, urna mortuária ou caixão).
    REGULAMENTO
</p>
<p>
    14. São direitos do contribuinte do contrato      __________
</p>
<p>
    <table>
        <tr>
            <td>1)Urna mortuária;</td>
            <td>7)Enfeites de flores naturais nas urnas</td>
        </tr>
        <tr>
            <td>2)Paramentação de metal;</td>
            <td>8)   ___   km de translado (ida e volta)</td>
        </tr>
        <tr>
            <td>3)Velas</td>
            <td>9)Cadeiras</td>
        </tr>
        <tr>
            <td>4)Tule</td>
            <td>10)Bebedouro c/ água mineral de 20 lts.</td>
        </tr>
        <tr>
            <td>5)Carro funerário para sepultamento</td>
            <td>11)Carro para remoção</td>
        </tr>
        <tr>
            <td>6)Café em pó e açúcar</td>
            <td>12)Nota de falecimento</td>
        </tr>
    </table>
</p>
<p>
    15. As partes elegem o foro da Comarca de Goiás, renuncia expressa de qualquer outro, por mais privilegiado que seja para dirimir
    possíveis duvidas emergentes do presente contrato.
</p>
<p>
    16. O beneficiário inscrito em mais de um contrato, terá seu atendimento prestado pelo primeiro que for solicitado, não cabendo pelas
    outras inscrições, qualquer indenização por estes mesmos serviços.
</p>
<p>
    RELAÇÃO DOS CONTRIBUINTES E SEUS DEPENDENTES INCLUIDOS NESTE CONTRATO
</p>
<p>
    Esposo (a):
</p>
<p>
    Filhos:
</p>
<p>
Pai:<br>
Mãe:<br>
Sogro:<br>
Sogra:<br>
Dependente:<br>
</p>
<p>
Goiás,  <b><?= date("d"); ?></b>  de <b><?= date("m"); ?></b> de <b><?= date("Y"); ?></b>
</p>
<p>
    <center>
        <table>
            <tr>
                <td>&nbsp</td>
                <td>______________________________</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>______________________________</td>

            </tr>
            <tr>
                <td>&nbsp</td>
                <td>João Batista Adair – ME</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>&nbsp</td>
                <td>Contratante</td>
            </tr>
        </table>
    </center>
</p>
<?php endforeach; ?></b>