<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            <?php
            /**
             * @var $assoc \Pax\Entity\PaxAssociados
             */

            foreach ($this->associado as $assoc): ?>
                Dependetes do Associado <?php echo $assoc->getNome(); ?>
            <?php endforeach;  ?>
        </div>
    </div>
    <div class="topo-table">
        <a href="<?php echo $this->url('pax-dependente/default', array('action' => 'inserir', 'id' => $assoc->getId()))?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
    </div>


    <div class="corpo-table">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Cpf</th>
                <th>Rg</th>
                <th>Status</th>
                <th>Data Nascimento</th>
                <th>Data Obito</th>
                <th>Tipo</th>
                <th>Opções</th>

            </tr>
            </thead>

            <tbody>
            <?php
            /**
             * @var $entity \Pax\Entity\PaxDependentes
             */
            ?>
            <?php  if ($this->data): ?>
                <?php foreach ($this->data as $entity): ?>
                    <tr>
                        <td><?php echo $entity->getId(); ?></td>
                        <td><?php echo $entity->getNome(); ?></td>
                        <td><?php echo $entity->getCpf(); ?></td>
                        <td><?php echo $entity->getRg(); ?></td>
                        <td><?php echo $entity->getStatus(); ?></td>
                        <td><?php echo ($entity->getDataNascimento()) ? $entity->getDataNascimento()->format('d/m/Y') : ""; ?></td>
                        <td><?php echo ($entity->getDataObito()) ? $entity->getDataObito()->format('d/m/Y') : ""; ?></td>
                        <td><?php echo $entity->getTipo(); ?></td>
                        <td>
                            <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('pax-dependente/default', array('action' => 'editar', 'id' => $entity->getId(),))?>"><span class="glyphicon glyphicon-edit"></span></a>
                            <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('pax-dependente/default', array("action" => "excluir", "id" => $entity->getId(),)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                        </td>


                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <p>Nem um Registro foi Encontrado</p>
            <?php endif;  ?>
            </tbody>
        </table>


    <div class="panel-footer">
        <a href="<?php echo $this->url('pax-associados/default')?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>


    <?php $this->headScript()->captureStart(); ?>
    $(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('pax-dependente/default', array("action" => "excluir")); ?>' + '/';

    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
    // variável contendo o id referente ao botão clicado
    var admin_id  = $(this).attr('href').split(url_deletar).pop();
    // variável contendo mensagem da janela
    var mensagem = "Deseja realmente apagar o Dependente com ID " + admin_id + "?";
    // variável com resposta da mensagem colocada na janela
    var confirmacao = confirm(mensagem);

    // se a confirmação for false o fluxo é interrompido
    if (!confirmacao)
    // elimar o evendo do botão clicado
    event.preventDefault();
    });
    });
<?php $this->headScript()->captureEnd(); ?>