<div class="pesquisa_pequena">
    <script>
        jQuery(document).ready(function(){
            $( "#nome" ).combogrid({
                url: '<?php echo $this->url('pax-associados/default', array('action' => 'pesquisas'))?>',
                debug:true,
                //replaceNull: true,
                colModel: [{'columnName':'id','width':'10','label':'Id'}, {'columnName':'nome','width':'60','label':'Nome'},{'columnName':'contrato','width':'30','label':'Contrato'}],
                select: function( event, ui ) {

                    $( "#nome" ).val( ui.item.nome );
                    return false;
                }
            });
        });
    </script>
</div>
<div class="panel panel-primary">
<div class="panel-heading">
    <div class="panel-title">
        Novo(a) Associados(a)
    </div>
</div>
<?php
// objeto form contato
$form = $this->form;
// preparar elementos do formulário
$form->prepare();
// configurar url formulário
$form->setAttribute('action', $this->url('pax-associados/default', array('controller' => 'associados', 'action' => 'inserir')));
?>

<?php // renderiza html <form> com atributos configurados no objeto ?>
<?php echo $this->form()->openTag($form) ?>
<div class="panel-body ">

<div class="container">

<div class='row'>
    <div class='form-group'>
        <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Cidade Ass.:</label>
        <div class='col-lg-4  col-md-4'>
            <?php
            // renderiza html input
            echo $this->formSelect($form->get('cidade_asso'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                ->setMessageOpenFormat("<small class='text-danger'>")
                ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                ->setMessageCloseString("</small>")
                ->render($form->get('cidade_asso'));
            ?>
        </div>
        <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Nome.:</label>
        <div class='col-lg-4  col-md-4'>
            <?php
            // renderiza html input
            echo $this->formInput($form->get('nome'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                ->setMessageOpenFormat("<small class='text-danger'>")
                ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                ->setMessageCloseString("</small>")
                ->render($form->get('nome'));
            ?>
        </div>
    </div>
</div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Contrato.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('contrato'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('contrato'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Data.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('data_contrato'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('data_contrato'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Pedido.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('data_pedido'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('data_pedido'));
                ?>
            </div>
        </div>
    </div>


    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Nascimento.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('data_nascimento'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('data_nascimento'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Dia Pag.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('dia_pagemento'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('dia_pagemento'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Grupo.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('serie'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('serie'));
                ?>
            </div>
        </div>
    </div>


    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Tipo Contrato.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('tipo_contrato'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('tipo_contrato'));
                ?>

            </div><label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Tipo Caixão.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('tipo_caixao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('tipo_caixao'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Viajem.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('viajem'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('viajem'));
                ?>
            </div>
        </div>
    </div>


    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Profissão.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('profissao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('profissao'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Religião.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('religiao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('religiao'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cobrador.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('vendedor'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('vendedor'));
                ?>
            </div>
        </div>
    </div>


    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Cep.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('cep'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('cep'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Estado.:</label>
            <div class='col-lg-2 col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('estado'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('estado'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cidade.:</label>
            <div class='col-lg-3  col-md-3'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('cidade'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('cidade'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Bairro.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('bairro'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('bairro'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Endereço.:</label>
            <div class='col-lg-3  col-md-3'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('endereco'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('endereco'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cobrança.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('endereco_cobranca'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('endereco_cobranca'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Celular.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('celular'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('celular'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Telefone.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('telefone'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('telefone'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Local.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('local'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('local'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Pai.:</label>
            <div class='col-lg-5  col-md-5'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('pai'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('pai'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Condição.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('status_pai'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('status_pai'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Mae.:</label>
            <div class='col-lg-5  col-md-5'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('mae'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('mae'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Condição.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('status_mae'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('status_mae'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Conjugue.:</label>
            <div class='col-lg-5  col-md-5'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('conjugue'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('conjugue'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Condição.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('status_conjugue'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('status_conjugue'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Cpf.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('cpf'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('cpf'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Rg.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('rg'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('rg'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Estado Civel.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('estado_civil'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('estado_civil'));
                ?>
            </div>


        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Translado.:</label>
            <div class='col-lg-4  col-md-4'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('translado'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('translado'));
                ?>
            </div>

        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Sogra.:</label>
            <div class='col-lg-5  col-md-5'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('nome_sogra'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('nome_sogra'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Condição.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('status_sogra'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('status_sogra'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Sogro.:</label>
            <div class='col-lg-5  col-md-5'>
                <?php
                // renderiza html input
                echo $this->formInput($form->get('nome_sogro'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('nome_sogro'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Condição.:</label>
            <div class='col-lg-2  col-md-2'>
                <?php
                // renderiza html input
                echo $this->formSelect($form->get('status_sogro'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('status_sogro'));
                ?>
            </div>
        </div>
    </div>

    <div class='row'>
        <div class='form-group'>
            <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Observação.:</label>
            <div class='col-lg-4  col-md-4'>
                <?php
                // renderiza html input
                echo $this->formTextArea($form->get('observacao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('observacao'));
                ?>
            </div>
            <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Cancelamento.:</label>
            <div class='col-lg-4  col-md-4'>
                <?php
                // renderiza html input
                echo $this->formTextArea($form->get('motivo_cancelamento'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat("<small class='text-danger'>")
                    ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                    ->setMessageCloseString("</small>")
                    ->render($form->get('motivo_cancelamento'));
                ?>
            </div>
        </div>
    </div>

</div>

</div>
<div class="panel-footer">
    <button type="submit" class="btn btn-primary">Salvar Associados(a)</button>
    <a href="<?php echo $this->url('pax-associados'); ?>" class="btn btn-default">Voltar</a>
</div>

<?php // renderiza html </form> ?>
<?php echo $this->form()->closeTag() ?>
</div>
