<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Nova Urna
        </div>
    </div>
    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('pax-move-caixa/default', array('controller' => 'move-caixa', 'action' => 'inserir')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel-body ">

        <div class="container">

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Discriminação.:</label>
                    <div class='col-lg-8  col-md-8'>
                        <?php
                        // renderiza html input
                        echo $this->formTextarea($form->get('discriminacao'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('discriminacao'));
                        ?>
                    </div>

                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Nome.:</label>
                    <div class='col-lg-2 col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('credor'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('credor'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Valor.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('valorLancado'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('valorLancado'));
                        ?>
                    </div>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Tipo.:</label>
                    <div class='col-lg-2  col-md-2'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('tipo'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('tipo'));
                        ?>
                    </div>

                </div>
            </div>


        </div>

    </div>
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Salvar Movimento</button>
        <a href="<?php echo $this->url('pax-move-caixa'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>
