<div class="pesquisa_pequena">
    <script>
        jQuery(document).ready(function(){
            $( "#project" ).combogrid({
                url: '<?php echo $this->url('pax-dependente/default', array('action' => 'pesquisas'))?>',
                debug:true,
                //replaceNull: true,
                colModel: [{'columnName':'id','width':'10','label':'Id'}, {'columnName':'nome','width':'60','label':'Nome'},{'columnName':'contrato','width':'30','label':'Contrato'}],
                select: function( event, ui ) {

                    $( "#project" ).val( ui.item.nome );
                    return false;
                }
            });
        });
    </script>
</div>
<div class="topo-table">
    <a href="<?php echo $this->url('pax-dependente/default', array('action' => 'inserir'))?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

    <form class="form-inline pull-right" method="post" role="form" action="<?php echo $this->url('pax-dependente/default', array('action' => 'pesquisa'))?>">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="localizar" class="form-control" id="project" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>De</th>
            <th>Ed</th>
            <th>PG</th>
            <th>Dep</th>
            <th>Con</th>
        </tr>
        <tr>
            <th>Detalhes</th>
            <th>Editar</th>
            <th>Pagamentos</th>
            <th>Dependetes</th>
            <th>Contrato</th>
        </tr>
    </table>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Lista Associados
        </div>
    </div>
</div>

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Associado</th>
            <th>Cidade</th>
            <th>Data Contrato</th>
            <th>Condição</th>
            <th>Status</th>
        </tr>
        </thead>

        <tbody>
        <?php
        /**
         * @var $entity \Pax\Entity\PaxDependentes
         */
        ?>
        <?php  if ($this->data): ?>
            <?php foreach ($this->data as $entity): ?>
                <tr>
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getNome(); ?></td>
                    <td><a href="<?php echo $this->url('pax-associados/default', array('action' => 'index', 'id' => $entity->getIdAssociado()->getId(),))?>"><?php echo $entity->getIdAssociado()->getNome(); ?></a></td>
                    <td><?php echo $entity->getTipo(); ?></td>
                    <td><?php echo ($entity->getDataNascimento()) ? $entity->getDataNascimento()->format('d/m/Y') : ""; ?></td>
                    <td><?php //echo $entity->getMensalidade($entity->getId()); ?></td>
                    <td><?php echo $entity->getStatus(); ?></td>


                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <p>Nem um Registro foi Encontrado</p>
        <?php endif;  ?>
        </tbody>
    </table>

    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator', array('router' => 'pax-dependente/paginator')); ?>


    <?php $this->headScript()->captureStart(); ?>
    $(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('pax-dependente/default', array("action" => "excluir")); ?>' + '/';

    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
    // variável contendo o id referente ao botão clicado
    var admin_id  = $(this).attr('href').split(url_deletar).pop();
    // variável contendo mensagem da janela
    var mensagem = "Deseja realmente apagar o Associado com ID " + admin_id + "?";
    // variável com resposta da mensagem colocada na janela
    var confirmacao = confirm(mensagem);

    // se a confirmação for false o fluxo é interrompido
    if (!confirmacao)
    // elimar o evendo do botão clicado
    event.preventDefault();
    });
    });
<?php $this->headScript()->captureEnd(); ?>