<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo(a) Dependente
        </div>
    </div>
    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('pax-dependente/default', array('controller' => 'dependentes', 'action' => 'inserir')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel-body ">

        <div class="container">

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Cód Ass.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('id_associado'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('id_associado'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Nome.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('nome'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('nome'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Cpf.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('cpf'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('cpf'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Rg.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('rg'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('rg'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Status.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('status'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('status'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Tipo.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('tipo'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('tipo'));
                        ?>
                    </div>
                </div>
            </div>

            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Nascimento.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('data_nascimento'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('data_nascimento'));
                        ?>
                    </div>
                </div>
            </div>


            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-2 control-label label_right'>Obito.:</label>
                    <div class='col-lg-3  col-md-3'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('data_obito'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('data_obito'));
                        ?>
                    </div>
                </div>
            </div>


        </div>

    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        //echo $this->formHidden($form->get('id_funcionarios')->setValue(1));
        // renderiza html input hidden csrf
        //echo $this->formElement($form->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dependente</button>
        <a href="<?php echo $this->url('pax-associados'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>